language: python
python:
  - "3.8.2" 
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install pylint
script:
#  - python3 -m unittest -v
  - cd src/delay_server
  - coverage run -m unittest discover -v
  - pylint --exit-zero delay_server
  - cd ../delay_client
  - coverage run -m unittest discover -v
  - pylint --exit-zero delay_client
  - cd ../../
  - coverage combine src/delay_server/.coverage src/delay_client/.coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - cd docs; sphinx-apidoc --ext-autodoc -o . ../source/; sphinx-build -a . ./_build/
#  - cd _static; pyreverse ../../source/calculator -a1 -s1 -o png

